version: '3.7'
services:
    # imagem micro 01
    micro_01:
        build:
            args:
                user: bruno
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        volumes:
            - ./:/var/www
        networks:
            - microservices

    # imagem nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8000:80
            - 443:443
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - microservices

    # imagem banco de dados
    micro_01_db:
        image: mysql:5.7.22
        restart: unless-stopped
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/data:/var/lib/mysql
        networks:
            - microservices

    # imagem phpmyadmin
    micro_01_phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        ports:
            - 8001:80
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: micro_01_db
            PMA_USER: ${DB_USERNAME}
            PMA_PASSWORD: ${DB_PASSWORD}
        links:
            - micro_01_db
        networks:
            - microservices

networks:
    microservices:
        driver: bridge
