version: '3.7'
services:
    # imagem micro 01
    app:
        build:
            args:
                user: ${DOCKER_USER}
                uid: ${DOCKER_UID}
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        volumes:
            - ./:/var/www
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - microservices_01

    # imagem nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8000:80
            #- 443:443
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - microservices_01

    # imagem banco de dados
    db:
        image: mysql:5.7.22
        restart: unless-stopped
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/data:/var/lib/mysql
        networks:
            - microservices_01

    # imagem phpmyadmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        ports:
            - 8085:80
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: db
            PMA_USER: ${DB_USERNAME}
            PMA_PASSWORD: ${DB_PASSWORD}
        links:
            - db
        networks:
            - microservices_01

networks:
    microservices_01:
        driver: bridge
